name = input("Enter Your Name:")
surname = input("Enter Your Surname:")
age = int(input("Enter Your Age:"))
city = input("Enter Your City:")
hobby = input("Enter Your Hobby:")
print (name + " " + surname)
print (age)
print (city)
print (hobby)
