name = str(input("Enter Your Name:"))
surname = str(input("Enter Your Surname:"))
age = int(input("Enter Your Age:"))
city = str(input("Enter Your City:"))
hobby = str(input("Enter Your Hobby:"))
print (name + " " + surname)
print (age)
print (city)
print (hobby)
